### ISSUE TITLE
Error: Invalid glob argument

### ISSUE THREAD

**Issue by JimmyDaddy** [Microsoft/app-metadata#5]
Hello, thank you for this useful package.
There are some problems when I install and use it.

* If I run `gulp build`, there will an error: 
```
[13:35:00] Starting 'core:build:typescript:client-test'...
The 'files' list in config file 'tsconfig.json' is empty.
[13:35:00] 'core:build:typescript:client-test' errored after 602 μs
[13:35:00] Error: Invalid glob argument:

``` 
Did you miss something in `tsconfig.json`?
* BTW, can you publish a build package to npm?  My project cant compiles this package because there are many "types" package missed.

**Comment by izikl** [comment]
@JimmyDaddy we are picking it up again. We are working on fixing all the test/build errors and create an NPM of it.
